namespace Glass.World;

///////////////////////////////////////////////////////////////////////////////////////////////
// SpellEffect
//
// One effect slot of a spell: the SPA number and its scaling inputs, stored exactly as
// parsed from the spell data file.  Base1 is the effect's primary value.  Base2 is
// SPA-specific auxiliary data, stored uninterpreted.  Calc selects the level-scaling
// formula applied to Base1; Max bounds the scaled magnitude, with zero meaning uncapped.
///////////////////////////////////////////////////////////////////////////////////////////////
public struct SpellEffect
{
    public uint Slot;
    public SPAId Spa;
    public int Base1;
    public int Base2;
    public uint Calc;
    public int Max;
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// SPAId
//
// The spell target effect (SPA) identifiers.  From a list posted by Prathun:
// https://forums.daybreakgames.com/eq/index.php?threads/enumerated-spa-list.206288/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
public enum SPAId
{
   Hitpoints = 0,
   ArmorClass = 1,
   AttackPower = 2,
   MovementRate = 3,
   Strength = 4,
   Dexterity = 5,
   Agility = 6,
   Stamina = 7,
   Intelligence = 8,
   Wisdom = 9,
   Charisma = 10,
   MeleeSpeed = 11,
   Invisibility = 12,
   SeeInvisibility = 13,
   EnduringBreath = 14,
   Mana = 15,                   // Mana Drain uses this
   NpcFrenzy = 16,
   NpcAwareness = 17,
   NpcAggro = 18,
   NpcFaction = 19,
   Blindness = 20,
   Stun = 21,
   Charm = 22,
   Fear = 23,
   Fatigue = 24,
   BindAffinity = 25,
   Gate = 26,
   DispelMagic = 27,
   InvisVsUndead = 28,
   InvisVsAnimals = 29,
   NpcReactRange = 30,
   Mesmerize = 31,
   CreateItem = 32,
   SpawnNpc = 33,
   Confuse = 34,
   Disease = 35,
   Poison = 36,
   DetectHostile = 37,
   DetectMagic = 38,
   NoTwincast = 39,
   Invulnerability = 40,
   Banish = 41,
   Shadowstep = 42,
   Berserk = 43,
   Lycanthropy = 44,
   Vampirism = 45,
   ResistFire = 46,
   ResistCold = 47,
   ResistPoison = 48,
   ResistDisease = 49,
   ResistMagic = 50,
   DetectTraps = 51,
   DetectUndead = 52,
   DetectSummoned = 53,
   DetectAnimals = 54,
   Stoneskin = 55,
   TrueNorth = 56,
   Levitation = 57,
   ChangeForm = 58,
   DamageShield = 59,
   TransferItem = 60,
   ItemLore = 61,
   ItemIdentify = 62,
   NpcWipeHatelist = 63,
   SpinStun = 64,
   Infravision = 65,
   Ultravision = 66,
   EyeOfZomm = 67,
   ReclaimEnergy = 68,
   MaxHitpoints = 69,
   CorpseBomb = 70,
   CreateUndead = 71,
   PreserveCorpse = 72,
   BindSight = 73,
   FeignDeath = 74,
   Ventriloquism = 75,
   Sentinel = 76,
   LocateCorpse = 77,
   SpellShield = 78,
   InstantHitpoints = 79,
   EnchantLight = 80,
   Resurrect = 81,
   SummonTarget = 82,
   Portal = 83,
   NpcOnlyHitpoints = 84,
   ContactAbility = 85,
   NpcHelpRadius = 86,
   Telescope = 87,
   Evacuate = 88,
   Height = 89,
   IgnorePet = 90,
   SummonCorpse = 91,
   Hate = 92,
   WeatherControl = 93,
   Fragile = 94,
   Sacrifice = 95,
   Silence = 96,
   MaxMana = 97,
   BardHaste = 98,
   Root = 99,
   HealOverTime = 100,
   CompleteHeal = 101,
   PetNoFear = 102,
   SummonPet = 103,
   Translocate = 104,
   NpcOnlyAntiGate = 105,
   BeastLordPet = 106,
   AlterPetLevel = 107,
   Familiar = 108,
   CreateItemInBag = 109,
   Resistances = 111,
   AdjustCastingSkill = 112,
   SummonMount = 113,
   ModifyHate = 114,
   Cornucopia = 115,
   Curse = 116,
   HitMagic = 117,
   Amplification = 118,
   BardHaste2 = 119,
   HealMod = 120,
   IronMaiden = 121,
   ReduceSkill = 122,
   Immunity = 123,
   FocusDamagePercent = 124,
   FocusHealMod = 125,
   FocusResistMod = 126,
   FocusCastTimeMod = 127,
   FocusDurationMod = 128,
   FocusRangeMod = 129,
   FocusHateMod = 130,
   FocusReagentMod = 131,
   FocusManacostMod = 132,
   FocusStuntimeMod = 133,
   FocusLevelMax = 134,
   FocusResistType = 135,
   FocusTargetType = 136,
   FocusWhichSPA = 137,
   FocusBeneficial = 138,
   FocusWhichSpell = 139,
   FocusDurationMinimum = 140,
   FocusInstantOnly = 141,
   FocusLevelMinimum = 142,
   FocusCasttimeMinimum = 143,
   FocusCasttimeMaximum = 144,
   NpcPortalWarderBanish = 145,
   PortalLocations = 146,
   PercentHeal = 147,
   StackingBlocker = 148,
   StripVirtualSlot = 149,
   DivineIntervention = 150,
   PocketPet = 151,
   PetSwarm = 152,
   DamageBalance = 153,
   CancelNegativeMagic = 154,
   PlaneOfPowerResurrect = 155,
   MirrorForm = 156,
   Feedback = 157,
   Reflect = 158,
   ModifyAllStats = 159,
   Inebriation = 160,
   SpellGuard = 161,
   MeleeGuard = 162,
   AbsorbHit = 163,
   ObjectSenseTrap = 164,
   ObjectDisarmTrap = 165,
   ObjectPicklock = 166,
   FocusPet = 167,
   Defensive = 168,
   CriticalMelee = 169,
   CriticalSpell = 170,
   CripplingBlow = 171,
   Evasion = 172,
   Riposte = 173,
   Dodge = 174,
   Parry = 175,
   DualWield = 176,
   DoubleAttack = 177,
   MeleeLifetap = 178,
   Puretone = 179,
   Sanctification = 180,
   Fearless = 181,
   HundredHands = 182,
   Accuracy = 184,
   SkillDamageMod1 = 185,
   MinDamageDone = 186,
   ManaBalance = 187,
   Block = 188,
   Endurance = 189,
   MaxEndurance = 190,
   Amnesia = 191,
   HateOverTime = 192,
   SkillAttack = 193,
   Fade = 194,
   StunResist = 195,
   SkillDamageTaken = 197,
   InstanceEndurance = 198,
   Taunt = 199,
   ProcChance = 200,
   RangeAbility = 201,
   IllusionOthers = 202,
   MassGroupBuff = 203,
   GroupFearImmunity = 204,
   Rampage = 205,
   AreaEffectTaunt = 206,
   FleshToBone = 207,
   PurgePoison = 208,
   CancelBeneficial = 209,
   ShieldCaster = 210,
   AreaEffectMelee = 211,
   FocusFrenziedDevastation = 212,
   PetPercentMaxHitpoints = 213,
   HitpointsMaxPercent = 214,
   PetAvoidancePercent = 215,
   MeleeAccuracy = 216,
   Headshot = 217,
   PetCriticalMelee = 218,
   SlayUndead = 219,
   IncreaseSkillDamage = 220,
   ReduceWeight = 221,
   BlockBehind = 222,
   DoubleRiposte = 223,
   AddRiposte = 224,
   GiveDoubleAttack = 225,
   TwoHandedBash = 226,
   ReduceSkillTimer = 227,
   ReduceFallDamage = 228,
   CastThroughStun = 229,
   IncreaseShieldDistance = 230,
   BashChance = 231,
   DivineSave = 232,
   Metabolism = 233,
   PoisonMastery = 234,
   FocusChanneling = 235,
   FreePet = 236,
   PetAffinity = 237,
   PermanentIllusion = 238,
   Stonewall = 239,
   StringUnbreakable = 240,
   ImprovedReclaimEnergy = 241,
   IncreaseMemwipeChance = 242,
   NoCharmBreakChance = 243,
   RootBreakChance = 244,
   TrapCircumvention = 245,
   IncreaseLungCapacity = 246,
   IncreaseSkillCap = 247,
   ExtraSpecialization = 248,
   OffhandMinimumWeaponDamage = 249,
   IncreaseProcChance = 250,
   EndlessQuiver = 251,
   FrontalBackstab = 252,
   ChatoticStab = 253,
   Nospell = 254,
   ShieldingDuration = 255,
   ShroudOfStealth = 256,
   GivePetHold = 257,
   TripleBackstab = 258,
   ArmorClassLimit = 259,
   AddInstrument = 260,
   SongModCap = 261,
   IncreaseStatisticCap = 262,
   TradeskillMastery = 263,
   ReduceAATimer = 264,
   NoFizzle = 265,
   AddTwoHandAttackChance = 266,
   AddPetCommands = 267,
   AlchemyFailRate = 268,
   FirstAid = 269,
   ExtendSongRange = 270,
   BaseRunMod = 271,
   IncreaseCastingLevel = 272,
   DamageOverTimeCritical = 273,
   HealingCritical = 274,
   MendCritical = 275,
   DualWieldAmount = 276,
   ExtraDIChance = 277,
   FinishingBlow = 278,
   Flurry = 279,
   PetFlurry = 280,
   PetFeignDeath = 281,
   IncreaseBandageAmount = 282,
   WuAttack = 283,
   ImproveLayOnHands = 284,
   NimbleEvasion = 285,
   FocusDamageAmount = 286,
   FocusDurationAmount = 287,
   AddProcHit = 288,
   DoomDuration = 289,
   IncreaseRunSpeedCap = 290,
   Purify = 291,
   Strikethrough = 292,
   StunResist2 = 293,
   SpellCriticalChance = 294,
   ReduceSpellTimer = 295,
   FocusDamageModDetrimental = 296,
   FocusDamageAmountDetrimental = 297,
   TinyCompanion = 298,
   WakeTheDead = 299,
   Doppleganger = 300,
   IncreaseRangeDamage = 301,
   FocusDamageModCritical = 302,
   FocusDamageAmountCritical = 303,
   SecondaryRiposteMod = 304,
   MitigateDamageShieldOffhand = 305,
   WakeTheDead2 = 306,
   Appraisal = 307,
   ZoneSuspendMinion = 308,
   TeleportCastersBindpoint = 309,
   FocusReuseTimer = 310,
   FocusCombatSkill = 311,
   Observer = 312,
   ForageMaster = 313,
   ImprovedInvisibility = 314,
   ImprovedInvisibilityVsUndead = 315,
   ImprovedInvisibilityVsAnimals = 316,
   IncreaseWornHitpointRegenCap = 317,
   IncreaseWornManaRegenCap = 318,
   CriticalHitpointRegen = 319,
   ShieldBlockChance = 320,
   ReduceTargetHate = 321,
   GateStartingCity = 322,
   DefensiveProc = 323,
   HitpointsForMana = 324,
   NoBreakAESneak = 325,
   AddSpellSlots = 326,
   AddBuffSlots = 327,
   IncreaseNegativeHitpointLimit = 328,
   ManaAbsorbPercentDamage = 329,
   CriticalAttackModifier = 330,
   AlchemyFailRecoverItem = 331,
   SummonToCorpse = 332,
   DoomRuneEffect = 333,
   HitpointsNoMove = 334,
   FocusedImmunity = 335,
   IllusionaryTarget = 336,
   IncreaseExperienceMod = 337,
   ExpedientRecovery = 338,
   FocusCastingProc = 339,
   ChanceSpell = 340,
   WornAttackCap = 341,
   NoPanic = 342,
   SpellInterrupt = 343,
   ItemChanneling = 344,
   AssassinateMaxLevel = 345,
   HeadshotMaxLevel = 346,
   DoubleRangedAttack = 347,
   FocusManaMinimum = 348,
   IncreaseShieldDamage = 349,
   Manaburn = 350,
   SpawnInteractiveObject = 351,
   IncreaseTrapCount = 352,
   IncreaseSOICount = 353,
   DeactivateAllTraps = 354,
   LearnTrap = 355,
   ChangeTriggerType = 356,
   FocusMute = 357,
   InstantMana = 358,
   PassiveSenseTrap = 359,
   ProcOnKillShot = 360,
   ProcOnDeath = 361,
   PotionBelt = 362,
   Bandolier = 363,
   AddTripleAttackChance = 364,
   ProcOnSpellKillShot = 365,
   GroupSheilding = 366,
   ModifyBodyType = 367,
   ModifyFaction = 368,
   Corruption = 369,
   ResistCorruption = 370,
   Slow = 371,
   GrantForaging = 372,
   DoomAlways = 373,
   TriggerSpell = 374,
   CriticalDotDamageMod = 375,
   Fling = 376,
   ResistOtherSPA = 378,
   DirectionalShadowstep = 379,
   ExplosiveKnockback = 380,
   FlingTowardCaster = 381,
   Suppression = 382,
   FocusCastingProcNormalized = 383,
   FlingCasterToward = 384,
   FocusWhichGroup = 385,
   DoomDispeller = 386,
   DoomDispellee = 387,
   SummonAllCorpses = 388,
   RefreshSpellTimer = 389,
   LockoutSpellTimer = 390,
   FocusManaMax = 391,
   FocusHealAmount = 392,
   FocusHealModBeneficial = 393,
   FocusHealAmountBeneficial = 394,
   FocusHealModCritical = 395,
   FocusHealAmountCritical = 396,
   AddPetArmorClass = 397,
   FocusSwarmPetDuration = 398,
   FocusTwincastChance = 399,
   Healburn = 400,
   ManaIgnite = 401,
   EnduranceIgnite = 402,
   FocusSpellClass = 403,
   FocusSpellSubclass = 404,
   StaffBlockChance = 405,
   DoomLimitUse = 406,
   DoomFocusUsed = 407,
   LimitHitpoints = 408,
   LimitMana = 409,
   LimitEndurance = 410,
   FocusLimitClass = 411,
   FocusLimitRace = 412,
   FocusBaseEffects = 413,
   FocusLimitSkill = 414,
   FocusLimitItemClass = 415,
   ArmorClass2 = 416,
   Mana2 = 417,
   FocusIncreaseSkillDamage2 = 418,
   ProcEffect2 = 419,
   FocusLimitUse = 420,
   FocusLimitUseAmount = 421,
   FocusLimitUseMinimum = 422,
   FocusLimutUseType = 423,
   Gravitate = 424,
   Fly = 425,
   AddExtendedTargetSlots = 426,
   SkillProc = 427,
   ProcSkillModifier = 428,
   SkillProcSuccess = 429,
   PostEffect = 430,
   PostEffectData = 431,
   ExpandMaxActiveTrophyBenefits = 432,
   AddNormalizedSkillMinimumDamageAmount = 433,
   AddNormalizedSkillMinimumDamageAmount2 = 434,
   FragileDefense = 435,
   ToggleFreezeBuffTimer = 436,
   TeleportToAnchor = 437,
   TranslocateToAnchor = 438,
   Assassinate = 439,
   FinishingBlowMaximum = 440,
   DistanceRemoval = 441,
   RequireTargetDoom = 442,
   RequireCasterDoom = 443,
   ImprovedTaunt = 444,
   AddMercenarySlot = 445,
   StackerA = 446,
   StackerB = 447,
   StackerC = 448,
   StackerD = 449,
   DotGuard = 450,
   MeleeThresholdGuard = 451,
   SpellThresholdGuard = 452,
   MeleeThresholdDoom = 453,
   SpellThresholdDoom = 454,
   AddHatePercent = 455,
   AddHateOverTimePercent = 456,
   ResourceTap = 457,
   FactionModifier = 458,
   SkillDamageModifier2 = 459,
   OverrideNotFocusable = 460,
   FocusDamageMod2 = 461,
   FocusDamageAmount2 = 462,
   ShieldTarget = 463,
   PlayerPetRampage = 464,
   PlayerPetAreaEffectRampage = 465,
   PlayerPetFlurry = 466,
   DamageShieldMitigationAmount = 467,
   DamageSheildMitigationPercent = 468,
   ChanceBestInSpellGroup = 469,
   TriggerBestInSpellGroup = 470,
   DoubleMeleeAttacks = 471,
   BuyNextAARank = 472,
   DoubleBackstabFront = 473,
   PetMeleeCriticalDamageMod = 474,
   TriggerSpellNonItem = 475,
   WeaponStance = 476,
   HatelistToTop = 477,
   HatelistToTail = 478,
   FocusLimitMinimumValue = 479,
   FocusLimitMaximumValue = 480,
   FocusCastSpellOnLand = 481,
   SkilLBaseDamageMod = 482,
   FocusIncomingDamageMod = 483,
   FocusIncomingDamageAmount = 484,
   FocusLimitCasterClass = 485,
   FocusLimitSameCaster = 486,
   ExtendTradeskillCap = 487,
   DefenderMeleeForcePercent = 488,
   WornEnduranceRegenCap = 489,
   FocusMinimumReuseTime = 490,
   FocusMaximumReuseTime = 491,
   FocusEnduranceMinimum = 492,
   FocusEnduranceMaximum = 493,
   PetAddAttack = 494,
   FocusDurationMaximum = 495,
   CriticalMeleeDamageModMaximum = 496,
   FocusCastProcNoBypass = 497,
   AddExtraPrimaryAttackPercent = 498,
   AddExtraSecondaryAttackPercent = 499,
   FocusCastTimeMod2 = 500,
   FocusCastTimeAmount = 501,
   FearStun = 502,
   MeleeDamagePositionMod = 503,
   MeleeDamagePositionAmount = 504,
   DamageTakenPositionMod = 505,
   DamageTakenPositionAmount = 506,
   AmplifyMod = 507,
   AmplifyAmount = 508,
   HealthTransfer = 509,
   FocusResistIncoming = 510,
   FocusTimerMinimum = 511,
   ProcTimerMod = 512,
   ManaMaximumPercent = 513,
   EnduranceMaximumPercent = 514,
   ArmorClassAvoidanceMaximumPercent = 515,
   ArmorClassMitigationMaximumPercent = 516,
   AttackOffsenseMaximumPercent = 517,
   AttackAccuracyMaximumPercent = 518,
   LuckAmount = 519,
   LuckPercent = 520,
   EnduranceAbsorbPercentDamage = 521,
   InstantManaPercent = 522,
   InstanceEndurancePercent = 523,
   DurationHitpointPercent = 524,
   DurationManaPercent = 525,
   DurationEndurancePercent = 526
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// SpellTargetType
//
// Target type values from spells_us.txt field 30. Determines what a spell may be cast upon and how
// recipients are selected. Values are the raw wire/file encodings.
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
public enum SpellTargetType : uint
{
    LineOfSight = 1,
    AePcV1 = 2,
    CasterGroup = 3,
    PointBlankAe = 4,
    Single = 5,
    Self = 6,
    TargetedAe = 8,
    Animal = 9,
    Undead = 10,
    Summoned = 11,
    Lifetap = 13,
    Pet = 14,
    Corpse = 15,
    Plant = 16,
    UberGiants = 17,
    UberDragons = 18,
    UndeadL55Max = 21,
    NpcHatelist = 32,
    NpcHatelist2 = 33,
    Chest = 34,
    PcOnly = 36,
    AreaNpcOnly = 37,
    SummonedPet = 38,
    NearbyPlayers = 40,
    TargetGroup = 41,
    DirectionalAe = 42,
    SinglePartyMember = 43,
    Beam = 44,
    TargetedAe2 = 45,
    TargetsTarget = 46,
    PetOwner = 47,
    TargetAeNotPlayerPet = 50,
    SingleFriendlyOrSelf = 51,
    SingleFriendlyOrTargetsTarget = 52
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// SpellCastRestriction
//
// Cast restriction values from spells_us.txt field 136. A nonzero value further constrains what the
// spell may be cast upon beyond the target type. Values are the raw file encodings; the value space
// is sparse and undefined values may appear in future patches.
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
public enum SpellCastRestriction : uint
{
    None = 0,
    AnimalOrHumanoid = 100,
    AnimalOrInsect = 102,
    Animal = 104,
    Plant = 105,
    Bixie = 109,
    Harpy = 110,
    Gnoll = 111,
    Sporali = 112,
    Kobold = 113,
    Shade = 114,
    Drakkin = 115,
    AnimalOrPlant = 117,
    Summoned = 118,
    FirePet = 119,
    Undead = 120,
    Living = 121,
    Fairy = 122,
    UndeadHpBelow10Pct = 124,
    ClockworkHpBelow45Pct = 125,
    WispHpBelow10Pct = 126,
    MeleeClassExceptBard = 127,
    PureMeleeClass = 128,
    PureCasterClass = 129,
    HybridClass = 130,
    NotWarriorPaladinShadowKnight = 148,
    NotRaidBoss = 190,
    HpBelow20Pct = 203,
    NotInCombat = 216,
    HpBelow35Pct = 250,
    ChainAndPlateClasses = 304,
    HpBelow35Pct2 = 507,
    HpBelow45Pct = 509,
    Humanoid = 601,
    Undead2 = 603,
    Dragon = 626,
    Npc = 700,
    NotPet = 701,
    Treant = 815,
    Bixie2 = 816,
    Scarecrow = 817,
    Undead3 = 818,
    NotUndead = 819,
    KnightAndHybridMeleeClasses = 820,
    WarriorCasterPriestClasses = 821,
    HasCrystallizedFlameBuff = 845,
    HasIncendiaryOozeBuff = 847,
    EsiantiAccess = 997
}

///////////////////////////////////////////////////////////////////////////////////////////////
// SpellRecord
//
// The retained fields of one spell from the spell data file.  Times are in milliseconds.
// DurationFormula selects the level-scaling formula that computes the buff duration;
// DurationCapTicks bounds the computed duration in six-second ticks, zero for instant
// effects.  PrimaryCategory is the client's own classification of the spell's role, with
// the secondary categories refining it, zero when unused.  ClassLevels holds the minimum
// level at which each class may cast the spell, indexed by class id minus one; the value
// 255 means the class cannot use the spell.  ReagentIds and NoExpendReagentIds hold item
// ids, -1 meaning no reagent; ReagentCounts gives the quantity expended per cast for the
// corresponding ReagentIds entry.  Effects holds only the effect slots whose SPA passed
// the parse-time whitelist, in slot order; a spell whose effects were all filtered has an
// empty array.
///////////////////////////////////////////////////////////////////////////////////////////////
public class SpellRecord
{
    public const uint ClassCount = 16;
    public const byte LevelUnusable = 255;

    public uint Id;
    public string Name = string.Empty;
    public uint Range;
    public uint CastTimeMs;
    public uint RecastTimeMs;
    public uint DurationFormula;
    public uint DurationCapTicks;
    public uint Mana;
    public uint PrimaryCategory;
    public uint SecondaryCategory;
    public uint SecondaryCategory2;
    public byte[] ClassLevels = new byte[ClassCount];
    public int[] ReagentIds = new int[4];
    public uint[] ReagentCounts = new uint[4];
    public int[] NoExpendReagentIds = new int[4];
    public SpellEffect[] Effects = Array.Empty<SpellEffect>();

    // Target type — what the spell may be cast upon.
    public SpellTargetType TargetType { get; set; }

    // Cast restriction — additional castability constraint, None when unrestricted.
    public SpellCastRestriction CastRestriction { get; set; }
}
